title: 'Citadel Swing'
default_lang: en
author:
  name: 'Citadel Swing'
  email: info@citadelswing.ro
taxonomies:
  - category
  - tag
metadata:
  description: 'WSDC Registry International West Coast Swing Event - 22-24 September 2017 - Timisoara, Romania.'
  referrer: always
  robots: all
  'og:type': website
  'og:locale': en_us
  'og:site_name': 'Citadel Swing 2017'
  'og:see_also': 'https://www.facebook.com/CitadelSwing'
  'og:image': /citadel-swing-2017-fb.jpg
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /schedule: /info/schedule
  /faqs: /info/faqs
  /the-plan: /info/the-plan
  /prices: /info/prices
  /marketplace: /info/marketplace
blog:
  route: /blog
jnj-registration-close: 'Saturday, 14:55'
workshops-start: 'Friday at 17:00'
jnj-competition-start: 'Saturday, 16:15'
themed-competition-start: 'Friday night at 22:00'
marketplace-open: 'Sunday from 17:30'
marketplace-close: '20:30'
marketplace-partners-list: 'to be announced'
jnj-levels-list: 'Newcomer, Novice, Intermediate and Advanced'
jnj-levels-number: '4'

